esphome:
  name: garage_esp8266
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

i2c:

switch:
  - id: garage_door_switch
    platform: gpio
    name: "Garage Door Switch"
    pin:
      number: D5
      inverted: true

cover:
  - platform: template
    name: "Garage Door"
    open_action:
      - switch.turn_on: garage_door_switch
      - delay: 0.2s
      - switch.turn_off: garage_door_switch
    close_action:
      - switch.turn_on: garage_door_switch
      - delay: 0.2s
      - switch.turn_off: garage_door_switch
    optimistic: true
    assumed_state: true

sensor:
  - platform: bme280
    address: 0x76
    temperature:
      name: "Garage Temperature"
    pressure:
      name: "Garage Pressure"
    humidity:
      name: "Garage Humidity"
  - platform: uptime
    name: "Garage Uptime"
  - platform: wifi_signal
    name: "Garage WiFi Strength"
